# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Stefan de Lange
CodeOfConductContact: Stefan de Lange
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.11'
License: MIT
LicenseCopyrightHolders: Stefan de Lange
MarkdownIndentation: 2
PackageName: OPF
PackageOwner: langestefan
PackageUUID: af201959-3ddc-5598-b8b4-065e4775240f
_commit: v0.15.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
